---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.scss"
exclude_paths:
- bin/