linters:
  Indentation:
    severity: warning
    width: 4
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  DeclarationOrder:
    enabled: false
  PropertySortOrder:
    enabled: false
  FinalNewline:
    enabled: false
  SpaceAfterPropertyColon:
    style: one_space_or_newline
  PlaceholderInExtend:
    enabled: false
  IdSelector:
    enabled: false
  QualifyingElement:
    enabled: false