language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
before_install:
  - npm install -g grunt-cli
  - gem install sass
  - npm install -g bower
install:
  - npm install
  - bower install
before_script: grunt